GET localhost:8080/api/v1/data/country/list
Accept: application/json

###

GET localhost:8080/api/v1/data/country/total
Accept: application/json

###

GET http://localhost:8080/api/v1/data/country/BOL/listhistoric
Accept: application/json

###

GET http://localhost:8080/api/v1/data/country/BOL/listhistoric/vaccine
Accept: application/json

###

GET http://localhost:8080/api/v1/data/country/BOL/historic
Accept: application/json

###