GET http://localhost:8080/api/v1/data/department/BO-L/total
Accept: application/json

###

GET http://localhost:8080/api/v1/data/department/BO-L/cumulative/list?page=375&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcl9uYW1lIjoianVhbnJvY2hhIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImV4cCI6MTYxODU0MDMyMCwidXNlck5hbWUiOiJqdWFucm9jaGEiLCJ1c2VySWQiOjEsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiOWI2NWIxNGYtYmJmNC00ODlhLThhZTgtMGQ0MjFlYWY5YTk0IiwiY2xpZW50X2lkIjoiY292aWR0cmFjZXJhcHAifQ.NnQ-Wx1oJY9GNRrYYa0o89AT3bFexgCcYo8nrNgzB7o
Accept: application/json

###