GET http://localhost:8080/api/v1/data/department/BO-L/total
Accept: application/json

###

GET http://localhost:8080/api/v1/data/department/BO-L/historic/list?page=375&size=10
Accept: application/json

###



GET http://localhost:8080/api/v1/data/department/BOL/list
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcl9uYW1lIjoianVhbnJvY2hhIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImV4cCI6MTYxODU3MDI4NywidXNlck5hbWUiOiJqdWFucm9jaGEiLCJ1c2VySWQiOjEsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiN2I2ZmUwZmUtOWE1Yy00OTM2LWJhNmYtYjM2MWNlNDk3ZDM5IiwiY2xpZW50X2lkIjoiY292aWR0cmFjZXJhcHAifQ.0YnMQ2JKaJljwspU-5SFeDNTnBusQY34PmRhFEIxJFg

###