GET localhost:8080/api/v1/data/country/list
Accept: application/json

###

GET localhost:8080/api/v1/data/country/total
Accept: application/json

###

GET http://localhost:8080/api/v1/data/country/BOL/historicList?page=375&size=10
Accept: application/json

###

GET http://localhost:8080/api/v1/data/country/BOL/CumulativeEveryDay?page=375&size=10
Accept: application/json

###

GET http://localhost:8080/api/v1/data/country/BOL/general
Accept: application/json

###

GET http://localhost:8080/api/v1/data/country/cumulative/list?page=430&size=50
Accept: application/json

###

GET http://localhost:8080/api/v1/data/country/world/total
Accept: application/json

###


GET http://localhost:8080/api/v1/data/country/BOL/totalCases
Accept: application/json

###
