POST http://localhost:8080/api/v1/user
Accept: application/json
Content-Type: application/json

{
  "firstName": "Juan",
  "firstSurname": "García",
  "secondSurname": "Mercado",
  "email": "juangracia@gmail.com",
  "userName": "juangarcia",
  "password": "juan123",
  "role": 2
}

###

PUT http://localhost:8080/api/v1/user
Accept: application/json
Content-Type: application/json

{
"userId": 1,
"passwordCurrent": "abc123456",
"passwordNew": "abc123455"
}

###